# Generated by Django 2.0.5 on 2018-09-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port_optimization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharpe_ratio_analysis',
            name='user',
        ),
        migrations.DeleteModel(
            name='sharpe_ratio_analysis',
        ),
    ]
